### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by bartoldeman**
Using 2to3 plus a few manual adjustments, and using the scipy-stack module for pexpect instead of including an old copy verbatim. Tested successfully.

### CODE REVIEW

**Comment by bartoldeman** [comment]
@mboisson @sergueev any feedback? Or are we sticking to Python 2 here?

**Comment by sergueev** [comment]
I checked the revisions by Bart (namely all python codes converted to python3, etc). First I couldn't make to work. Apparently the Part 2 Authenticating with Mediawiki in the upload-to-wikiAPI.sh had some issues.  It failed to authenticate with a given token. Here is the code that has caused errors:
--data-urlencode "username=${USERNAME}" \
--data-urlencode "password=${USERPASS}" \
--data-urlencode "rememberMe=1" \
--data-urlencode "logintoken=${TOKEN}" \
--data-urlencode "loginreturnurl=http://en.wikipedia.org" \
--request "POST" "${WIKIAPI}?action=clientlogin&format=json")
It simple didn't recognize values like username, password, rememberMe, etc.

When I looked at the currently working version. It has something different:
--data-urlencode "lgname=${USERNAME}" \
--data-urlencode "lgpassword=${USERPASS}" \
--data-urlencode "lgtoken=${TOKEN}" \
--request "POST" "${WIKIAPI}?action=login&format=json")

I think probably Bart has forked the original wiki_module_bot and it was not up to date.  

Anyway, after I replaced those several lines it worked just fine.
However, what's funny is that even with the failed Part 2, Part 3 was able to fetch the edit token and then push the edits successfully. Hmm, it's puzzling to me.

Bart, can you change those line in the upload-to-wikiAPI.sh  file in your py3 branch and then we can merge I guess ?

**Comment by bartoldeman** [comment]
I could not fork from anything else than the original wiki_module_bot since the up-to-date one wasn't pushed anywhere.
We have to first make what's here on github up to date with what's in prod.
That's done in PRs #6 #7 #8 and #9 (the latter changes a bit, by using a higher level module path, but the result works)

**Comment by sergueev** [comment]
I agree. First,  I am gonna go ahead and update the main branch to the current version that we have on cvmfs-client server.  Then we can update again to include python3 changes.

**Pull request merged**
